

export const sample_foods: any[] = [
  {
    id:1,
    price:2500,
    name: 'Samsung LED TV', 

    cookTime:'10-20',
    favorite:false,
    stars:4.5,
    origins: ['pakistan'],
    imageUrl:'/assets/4.png',
    tags:['LED TV'],
  
},
  {
    id: 2,
    name: '65" QLED 4K Q70B',
    price: 2200,
    cookTime: '15-20',
    favorite: false,
    origins: ['italian'],
    stars: 4.1,
    imageUrl: '/assets/5.png',
    tags: ['LED TV'],
  },
  {
    id: 3,
    name: 'AU7000 UHD 4K Smart TV',
    price: 1000,
    cookTime: '10-20',
    favorite: false,
    origins: ['german'],
    stars: 4.0,
    imageUrl: '/assets/6.png',
    tags: ['LED TV'],
  },
  {
    id: 4,
    name: '65" QLED 4K Q80B',
    price: 1450,
    cookTime: '20-30',
    favorite: false,
    origins: ['persian', 'middle east'],
    stars: 4.7,
    imageUrl: '/assets/7.png',
    tags: ['LED TV'],
  },
  {
    id: 5,
    name: 'QN900A Neo QLED 8K Smart TV (2021)',
    price: 1600,
    cookTime: '15-20',
    favorite: false,
    origins: ['german', 'italian'],
    stars: 4.0,
    imageUrl: '/assets/8.png',
    tags: ['fastfood', 'pizza', 'lunch'],
  },
  {
    id: 6,
    name: 'QN85A Neo QLED 4K Smart TV',
    price: 1700,
    cookTime: '10-20',
    favorite: false,
    origins: ['pakistani', 'italian'],
    stars: 4.0,
    imageUrl: '/assets/9.png',
    tags: ['fastfood', 'pizza', 'lunch'],
  },
  {
    id: 7,
    name: 'QN85A Neo QLED 4K Smart TV',
    price: 2000,
    cookTime: '20-30',
    favorite: false,
    origins: ['china', 'german'],
    stars: 3.0,
    imageUrl: '/assets/10.png',
    tags: ['fastfood', 'noodles', 'lunch', 'dinner'],
  },
  {
    id: 8,
    name: 'Apple MacBook Air 13.3" M1 Chip MGN93 Silver (Late 2020) | Non Active',
    price: 1200,
    cookTime: '15-20',
    favorite: false,
    origins: ['pakistani'],
    stars: 4.0,
    imageUrl: '/assets/11.jpg',
    tags: ['fastfood', 'sandwich', 'lunch'],
  },
  {
    id: 9,
    name: 'Apple MacBook Air 13.6" - M2 Chip',
    price: 1100,
    cookTime: '15-20',
    favorite: false,
    origins: ['pakistani'],
    stars: 4.0,
    imageUrl: '/assets/12.jpg',
    tags: ['fastfood', 'sandwich', 'lunch'],
  },
  {
    id: 10,
    name: 'Apple MacBook Air 13.6" - M2 Chip, Silver',
    price: 1500,
    cookTime: '15-20',
    favorite: false,
    origins: ['pakistani'],
    stars: 4.0,
    imageUrl: '/assets/13.jpg',
    tags: ['fastfood', 'sandwich', 'lunch'],
  },
  {
    id: 11,
    name: 'Apple MacBook Air 13.6" - M2 Chip, Grey',
    price: 15,
    cookTime: '15-20',
    favorite: false,
    origins: ['pakistani'],
    stars: 4.0,
    imageUrl: '/assets/14.jpg',
    tags: ['fastfood', 'sandwich', 'lunch'],
  },
  {
    id: 12,
    name: '  M1 Chip MYD92 Space Gray ',
    price: 15,
    cookTime: '15-20',
    favorite: false,
    origins: ['pakistani'],
    stars: 4.0,
    imageUrl: '/assets/15.jpg',
    tags: ['fastfood', 'sandwich', 'lunch'],
  },
  {
    id: 13,
    name: 'J4107 14.1 Inch RAM 6GB DDR4 ROM 128GB 256GB',
    price: 15,
    cookTime: '15-20',
    favorite: false,
    origins: ['pakistani'],
    stars: 4.0,
    imageUrl: '/assets/17.jpg',
    tags: ['fastfood', 'sandwich', 'lunch'],
  },
  {
    id: 14,
    name: 'J4105 14.1 Inch RAM DDR4 6GB ROM 128GB 512GB',
    price: 15,
    cookTime: '15-20',
    favorite: false,
    origins: ['pakistani'],
    stars: 4.0,
    imageUrl: '/assets/16.jpg',
    tags: ['fastfood', 'sandwich', 'lunch'],
  },
  {
    id: 15,
    name: 'J4106 14.1 Inch RAM 6GB DDR4 ROM 128GB 256GB',
    price: 15,
    cookTime: '15-20',
    favorite: false,
    origins: ['pakistani'],
    stars: 4.0,
    imageUrl: '/assets/18.jpg',
    tags: ['fastfood', 'sandwich', 'lunch'],
  },
  {
    id: 16,
    name: 'QMDZ Narrow Border 15.6-inch IPS Screen 16GB RAM 256GB',
    price: 15,
    cookTime: '15-20',
    favorite: false,
    origins: ['pakistani'],
    stars: 4.0,
    imageUrl: '/assets/19.jpg',
    tags: ['fastfood', 'sandwich', 'lunch'],
  },
  {
    id: 17,
    name: ' SSD HDMI Notebook Fingerprint Unlock Intel Cheap Laptop 15.6 ',
    price: 15,
    cookTime: '15-20',
    favorite: false,
    origins: ['pakistani'],
    stars: 4.0,
    imageUrl: '/assets/21.webp',
    tags: ['fastfood', 'sandwich', 'lunch'],
  },
  {
    id: 18,
    name: 'AKPAD Laptop 15.6-inch IPS Screen 16GB RAM SATA SSD',
    price: 15,
    cookTime: '15-20',
    favorite: false,
    origins: ['pakistani'],
    stars: 4.0,
    imageUrl: '/assets/22.jpg',
    tags: ['fastfood', 'sandwich', 'lunch'],
  },
  {
    id: 19,
    name: 'OMEN Gaming Laptop 16-k0360TX',
    price: 15,
    cookTime: '15-20',
    favorite: false,
    origins: ['pakistani'],
    stars: 4.0,
    imageUrl: '/assets/24.webp',
    tags: ['fastfood', 'sandwich', 'lunch'],
  },
  {
    id: 20,
    name: 'HP Laptop 15s',
    price: 15,
    cookTime: '15-20',
    favorite: false,
    origins: ['pakistani'],
    stars: 4.0,
    imageUrl: '/assets/23.webp',
    tags: ['fastfood', 'sandwich', 'lunch'],
  },
  //26
  {
    id: 21,
    name: 'HP Laptop 16x Gaming',
    price: 15,
    cookTime: '15-20',
    favorite: false,
    origins: ['pakistani'],
    stars: 4.0,
    imageUrl: '/assets/24.webp',
    tags: ['fastfood', 'sandwich', 'lunch'],
  },
  //27
  {
    id: 22,
    name: 'INTEL CORE i5 11400 BOXED WITH WARRANTY',
    price: 15,
    cookTime: '15-20',
    favorite: false,
    origins: ['pakistani'],
    stars: 4.0,
    imageUrl: '/assets/25.webp',
    tags: ['fastfood', 'sandwich', 'lunch'],
  },
  {
    id: 23,
    name: 'INTEL CORE i7 12400 BOXED WITH WARRANTY',
    price: 15,
    cookTime: '15-20',
    favorite: false,
    origins: ['pakistani'],
    stars: 4.0,
    imageUrl: '/assets/26.webp',
    tags: ['fastfood', 'sandwich', 'lunch'],
  },
  {
    id: 24,
    name: 'Core i5 12400 12TH GEN',
    price: 15,
    cookTime: '15-20',
    favorite: false,
    origins: ['pakistani'],
    stars: 4.0,
    imageUrl: '/assets/27.webp',
    tags: ['fastfood', 'sandwich', 'lunch'],
  },
  //28//
  {
    id: 25,
    name: 'ASUS ROG XXL RGB KEYBOARD PLUS MOUSE PAD',
    price: 15,
    cookTime: '15-20',
    favorite: false,
    origins: ['pakistani'],
    stars: 4.0,
    imageUrl: '/assets/28.webp',
    tags: ['fastfood', 'sandwich', 'lunch'],
  },
  {
    id: 26,
    name: '1st Player DK 9.0 DEATH KNIGHT Keyboard, Mouse, Headset, Mousepad Gaming Kit',
    price: 15,
    cookTime: '15-20',
    favorite: false,
    origins: ['pakistani'],
    stars: 4.0,
    imageUrl: '/assets/29.webp',
    tags: ['fastfood', 'sandwich', 'lunch'],
  },
  {
    id: 27,
    name: 'K8 Gaming / Office Keyboard and Mouse Kit',
    price: 15,
    cookTime: '15-20',
    favorite: false,
    origins: ['pakistani'],
    stars: 4.0,
    imageUrl: '/assets/30.webp',
    tags: ['fastfood', 'sandwich', 'lunch'],
  },
  {
    id: 28,
    name: 'Redragon EPEIUS P009 GAMING MOUSE MAT',
    price: 15,
    cookTime: '15-20',
    favorite: false,
    origins: ['pakistani'],
    stars: 4.0,
    imageUrl: '/assets/31.webp',
    tags: ['fastfood', 'sandwich', 'lunch'],
  },
  //32 new add
  {
    id: 29,
    name: 'Mouse Pad',
    price: 15,
    cookTime: '15-20',
    favorite: false,
    origins: ['pakistani'],
    stars: 4.0,
    imageUrl: '/assets/32.webp',
    tags: ['fastfood', 'sandwich', 'lunch'],
  },
  {
    id: 30,
    name: 'Gaming LED HD+',
    price: 15,
    cookTime: '15-20',
    favorite: false,
    origins: ['pakistani'],
    stars: 4.0,
    imageUrl: '/assets/33.webp',
    tags: ['fastfood', 'sandwich', 'lunch'],
  },
  {
    id: 31,
    name: 'MSI Optix G27C5 165HZ',
    price: 15,
    cookTime: '15-20',
    favorite: false,
    origins: ['pakistani'],
    stars: 4.0,
    imageUrl: '/assets/34.webp',
    tags: ['fastfood', 'sandwich', 'lunch'],
  },
  {
    id: 32,
    name: 'Alseye M240 Plus',
    price: 15,
    cookTime: '15-20',
    favorite: false,
    origins: ['pakistani'],
    stars: 4.0,
    imageUrl: '/assets/35.webp',
    tags: ['fastfood', 'sandwich', 'lunch'],
  },
  {
    id: 33,
    name: '980 PRO SAMSUNG 250GB',
    price: 15,
    cookTime: '15-20',
    favorite: false,
    origins: ['pakistani'],
    stars: 4.0,
    imageUrl: '/assets/36.webp',
    tags: ['fastfood', 'sandwich', 'lunch'],
  },
  {
    id: 34,
    name: 'Adata 32GB UV150 USB 3.2 Flash Drive – Black',
    price: 15,
    cookTime: '15-20',
    favorite: false,
    origins: ['pakistani'],
    stars: 4.0,
    imageUrl: '/assets/37.webp',
    tags: ['fastfood', 'sandwich', 'lunch'],
  },
  {
    id: 35,
    name: '1980 PRO SAMSUNG 250GB',
    price: 15,
    cookTime: '15-20',
    favorite: false,
    origins: ['pakistani'],
    stars: 4.0,
    imageUrl: '/assets/38.webp',
    tags: ['fastfood', 'sandwich', 'lunch'],
  },
  //39new
  {
    id: 36,
    name: 'Corsair Vengeance RGB PRO SL 8*2 3600 MHZ NEW MODEL',
    price: 15,
    cookTime: '15-20',
    favorite: false,
    origins: ['pakistani'],
    stars: 4.0,
    imageUrl: '/assets/39.webp',
    tags: ['fastfood', 'sandwich', 'lunch'],
  },
  {
    id: 37,
    name: 'CORSAIR VENGEANCE PRO 3200 MHZ 16 GB (8*2 MODULES) CL 16',
    price: 15,
    cookTime: '15-20',
    favorite: false,
    origins: ['pakistani'],
    stars: 4.0,
    imageUrl: '/assets/40.webp',
    tags: ['fastfood', 'sandwich', 'lunch'],
  },
  {
    id: 38,
    name: 'CORSAIR VENGEANCE LPX 3200 16GB (2 x 8GB)',
    price: 15,
    cookTime: '15-20',
    favorite: false,
    origins: ['pakistani'],
    stars: 4.0,
    imageUrl: '/assets/41.webp',
    tags: ['fastfood', 'sandwich', 'lunch'],
  },
  {
    id: 39,
    name: 'DDR3 8GB RAM USED',
    price: 15,
    cookTime: '15-20',
    favorite: false,
    origins: ['pakistani'],
    stars: 4.0,
    imageUrl: '/assets/42.webp',
    tags: ['fastfood', 'sandwich', 'lunch'],
  },
  
];


export const sample_tags:any[] = [
  { name: 'All', count: 6 },
  { name: 'LED TV', count: 4 },
  { name: 'LAPTOP', count: 2 },
  { name: 'RAM', count: 3 },
  { name: 'KEYBOARD', count: 2 },
 { name: 'DDR4', count: 1 },
 { name: 'MOUSE', count: 1 },
  { name: 'COREI5', count: 1 },
]

export const sample_users:any[] = [
  { 
   name: "John Doe",
   email: "john@gmail.com",
   password: "12345",
   address: "Toronto On",
   isAdmin: true,
},
{ 
name: "Jane Doe",
email: "najam@gmail.com",
password: "12345",
address: "Shanghai",
isAdmin: false,

},
];
